# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "biasresistor"
BBFILE_PATTERN_biasresistor = "^${LAYERDIR}/"
BBFILE_PRIORITY_biasresistor = "6"

LAYERDEPENDS_biasresistor = "core"
LAYERSERIES_COMPAT_biasresistor = "scarthgap styhead walnascar"
